SELECT 
    A.NAME,
    TEAM,
    AGE,
    POSITION,
    MATCHES_PLAYED,
    STARTS,
    MINUTES,
    GOALS,
    ASSISTS,
    PENALTIES,
    PENALTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    xA,
    B.OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    A.SEASON_START,
    POINTS,
FROM {{ ref('1_FBREF_ALL_SEASONS') }} A 
INNER JOIN (SELECT * FROM {{ ref('1_FPL_ALL_SEASONS') }}) B
    ON A.NAME = B.NAME
WHERE A.SEASON_START = B.SEASON_START 
