SELECT 
    A.NAME,
    A.AGE,
    A.POSITION,
    A.TEAM,
    A.MATCHES_PLAYED,
    A.STARTS,
    A.MINUTES,
    A.GOALS,
    A.ASSISTS,
    A.PENALTIES,
    A.PENALTIES_MISSED,
    A.YELLOW_CARDS,
    A.RED_CARDS,
    A.xG,
    A.xA,
    A.OWN_GOALS,
    A.GOALS_CONCEDED,
    A.CLEAN_SHEETS,
    A.SAVES,
    A.SEASON_START,
    A.POINTS,
    B.POINTS AS NEXT_SEASON_POINTS
FROM {{ ref('2_FBREF_FPL') }} A 
LEFT JOIN (SELECT * FROM {{ ref('1_FPL_ALL_SEASONS') }}) B
    ON (B.NAME LIKE CONCAT("%", A.NAME, "%") 
        OR A.NAME LIKE CONCAT("%", B.NAME, "%")) 
        AND (A.SEASON_START = B.SEASON_START + 1)