WITH CLEANED_SEASONS AS (
  SELECT 
    NAME,
    AGE,
    TEAM_RANK,
    SEASON_START,
    POSITION,
    MATCHES_PLAYED,
    SAFE_DIVIDE(MINUTES, MATCHES_PLAYED) AS MINUTES_PER_GAME,
    STARTS,
    MINUTES,
    GOALS,
    SAFE_DIVIDE(MINUTES, GOALS) AS MINUTES_PER_GOAL,
    ASSISTS,
    SAFE_DIVIDE(MINUTES, ASSISTS) AS MINUTES_PER_ASSIST,
    PENALTIES,
    PEANLTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    SAFE_DIVIDE(MINUTES, xG) AS MINUTES_PER_XG,
    GOALS - xG AS XG_DIFF,
    xA,
    SAFE_DIVIDE(MINUTES, xA) AS MINUTES_PER_XA,
    ASSISTS - xA AS XA_DIFF,
    OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    POINTS,
    SAFE_DIVIDE(MINUTES, POINTS) AS MINUTES_PER_POINT,
    NEXT_SEASON_POINTS
  FROM {{ ref('5_CLEANED') }} 
)

SELECT *
FROM CLEANED_SEASONS
WHERE MATCHES_PLAYED < 39