WITH CLEANED_SEASONS AS (
  SELECT 
    NAME,
    AGE,
    TEAM_RANK,
    POSITION,
    MATCHES_PLAYED,
    STARTS,
    MINUTES,
    GOALS,
    ASSISTS,
    PENALTIES,
    PEANLTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    xA,
    OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    POINTS,
    NEXT_SEASON_POINTS
  FROM {{ ref('5_CLEANED') }} 
  GROUP BY NAME, POSITION, AGE
)

SELECT *
FROM CLEANED_SEASONS