WITH FE_SEASONS AS (
  SELECT 
    A.NAME,
    AGE,
    TEAM_RANK,
    A.POSITION,
    MATCHES_PLAYED,
    STARTS,
    MINUTES,
    MINUTES_PER_GOAL,
    MINUTES_PER_ASSIST,
    MINUTES_PER_POINT,
    MINUTES_PER_XG,
    MINUTES_PER_XA,
    MINUTES_PER_GAME,
    GOALS,
    ASSISTS,
    PENALTIES,
    PEANLTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    GOALS - xG AS XG_DIFF,
    xA,
    ASSISTS - xA AS XA_DIFF,
    OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    COST,
    POINTS,
  FROM {{ ref('4_FACTOR_ENGINEERING') }} A
  INNER JOIN {{ source('live', 'prices') }} B ON A.NAME = B.NAME
  WHERE SEASON_START = (SELECT MAX(SEASON_START) FROM {{ ref('4_FACTOR_ENGINEERING') }})
)

SELECT *
FROM FE_SEASONS