WITH FE_SEASONS AS (
  SELECT 
    NAME,
    AGE,
    TEAM_RANK,
    POSITION,
    MATCHES_PLAYED,
    STARTS,
    MINUTES,
    MINUTES_PER_GOAL,
    MINUTES_PER_ASSIST,
    MINUTES_PER_POINT,
    MINUTES_PER_XG,
    MINUTES_PER_XA,
    MINUTES_PER_GAME,
    GOALS,
    ASSISTS,
    PENALTIES,
    PEANLTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    GOALS - xG AS XG_DIFF,
    xA,
    ASSISTS - xA AS XA_DIFF,
    OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    POINTS,
  FROM {{ ref('4_fe') }} 
  WHERE SEASON_START = (SELECT MAX(SEASON_START) FROM {{ ref('4_fe') }})
)

SELECT *
FROM FE_SEASONS