WITH FULL_SEASONS_GROUPED AS (
  SELECT 
    LOWER(NAME) AS NAME,
    AGE,
    AVG(TEAM_RANK) AS TEAM_RANK,
    CASE
        WHEN POSITION = "FW,MF"
        THEN "MF"
        ELSE SUBSTR(POSITION, 1, 2)
    END AS POSITION, 
    -- Issue with Cold Palmer, has points doubled, worth fixing?
    SEASON_START,
    SUM(CAST(MATCHES_PLAYED AS INT64)) AS MATCHES_PLAYED,
    SUM(STARTS) AS STARTS,
    SUM(MINUTES) AS MINUTES,
    SUM(GOALS) AS GOALS,
    SUM(ASSISTS) AS ASSISTS,
    SUM(PENALTIES) AS PENALTIES,
    SUM(PENALTIES_MISSED) AS PENALTIES_MISSED,
    SUM(YELLOW_CARDS) AS YELLOW_CARDS,
    SUM(RED_CARDS) AS RED_CARDS,
    SUM(xG) AS xG,
    SUM(xA) AS xA,
    SUM(OWN_GOALS) AS OWN_GOALS,
    SUM(GOALS_CONCEDED) AS GOALS_CONCEDED,
    SUM(CLEAN_SHEETS) AS CLEAN_SHEETS,
    SUM(SAVES) AS SAVES,
    SUM(POINTS) AS POINTS,
    SUM(NEXT_SEASON_POINTS) AS NEXT_SEASON_POINTS
  FROM {{ ref('2_FBREF_FPL_PL') }} 
  GROUP BY NAME, POSITION, AGE, SEASON_START
)

SELECT *
FROM FULL_SEASONS_GROUPED