WITH TO_PREDICT_GROUPED AS (
  SELECT 
    LOWER(NAME) AS NAME,
    AGE,
    AVG(TEAM_RANK) AS TEAM_RANK,
    MIN(POSITION) AS POSITION,
    SUM(MATCHES_PLAYED) AS MATCHES_PLAYED,
    SUM(STARTS) AS STARTS,
    SUM(MINUTES) AS MINUTES,
    SUM(GOALS) AS GOALS,
    SUM(ASSISTS) AS ASSISTS,
    SUM(PENALTIES) AS PENALTIES,
    SUM(PENALTIES_MISSED) AS PEANLTIES_MISSED,
    SUM(YELLOW_CARDS) AS YELLOW_CARDS,
    SUM(RED_CARDS) AS RED_CARDS,
    SUM(xG) AS xG,
    SUM(xA) AS xA,
    SUM(OWN_GOALS) AS OWN_GOALS,
    SUM(GOALS_CONCEDED) AS GOALS_CONCEDED,
    SUM(CLEAN_SHEETS) AS CLEAN_SHEETS,
    SUM(SAVES) AS SAVES,
    SUM(POINTS) AS POINTS,
  FROM {{ ref('4_FBREF_FPL_PL') }} 
  WHERE SEASON_START = 2023
  GROUP BY NAME, AGE
)

SELECT *
FROM TO_PREDICT_GROUPED