SELECT 
    A.NAME,
    TEAM,
    AGE,
    POSITION,
    MATCHES_PLAYED,
    STARTS,
    MINUTES,
    GOALS,
    ASSISTS,
    PENALTIES,
    PENALTIES_MISSED,
    YELLOW_CARDS,
    RED_CARDS,
    xG,
    xA,
    OWN_GOALS,
    GOALS_CONCEDED,
    CLEAN_SHEETS,
    SAVES,
    POINTS,
FROM {{ ref('1_FBREF_ALL_SEASONS') }} A 
LEFT JOIN (SELECT * FROM {{ ref('1_FPL_ALL_SEASONS') }}) B
    ON (B.NAME LIKE CONCAT("%", A.NAME, "%") 
        OR A.NAME LIKE CONCAT("%", B.NAME, "%")) 
        AND A.SEASON_START = B.SEASON_START