-- models/full_seasons_grouped.sql
WITH full_seasons_grouped AS (
  SELECT 
    LOWER(NAME) AS NAME,
    AGE,
    AVG(TEAM_RANK) AS TEAM_RANK,
    MIN(POSITION) AS POSITION,
    SUM(MATCHES_PLAYED) AS MATCHES_PLAYED,
    SUM(STARTS) AS STARTS,
    SUM(MINUTES) AS MINUTES,
    SUM(GOALS) AS GOALS,
    SUM(ASSISTS) AS ASSISTS,
    SUM(PENALTIES) AS PENALTIES,
    SUM(PENALTIES_MISSED) AS PENALTIES_MISSED,
    SUM(YELLOW_CARDS) AS YELLOW_CARDS,
    SUM(RED_CARDS) AS RED_CARDS,
    SUM(xG) AS xG,
    SUM(xA) AS xA,
    SUM(OWN_GOALS) AS OWN_GOALS,
    SUM(GOALS_CONCEDED) AS GOALS_CONCEDED,
    SUM(CLEAN_SHEETS) AS CLEAN_SHEETS,
    SUM(SAVES) AS SAVES,
    SUM(POINTS) AS POINTS,
    MAX(NEXT_SEASON_POINTS) AS NEXT_SEASON_POINTS
  FROM {{ ref('full_seasons') }}
  GROUP BY NAME, AGE
)
SELECT * FROM full_seasons_grouped
WHERE NEXT_SEASON_POINTS IS NOT NULL;